apiVersion: v1
kind: Pod
metadata:
  name: consumer
  labels:
    app: myconsumer
spec:
  containers:
    - name: consumer
      image: muteebakram/consumer:2
      command: ["python", "-u", "./consumer.py"]